version: "3"
services:
  web:
    container_name: nginx_web
    image:  nginx:1.13.7
    # ports:
      # - "80:80"
    volumes:
      # put index.html in folder html would mount into conatiner
      - ./html1:/usr/share/nginx/html/html1
      - ./html2:/usr/share/nginx/html/html2
      # put default.conf in folder conf would moutn into ...
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # put nginx.conf outside
      - ./nginx.conf:/etc/nginx/nginx.conf
      # mount ssl
      # - ./ssl:/etc/nginx/ssl
      # mount nginx logs
      # - ./log:/var/log/nginx
  nginx:
    container_name: nginx_proxy
    image:  nginx:1.13.7
    ports:
      - "80:80"
    volumes:
      # put default.conf in folder conf would moutn into ...
      - ./default_proxy.conf:/etc/nginx/conf.d/default.conf