apiVersion: v1
kind: Service
metadata:
  name: redis-commander-service
  labels:
    app: redis-commander
spec:
  # type: LoadBalancer # use extenal IP
  type: NodePort # use NAT inside k8s
  selector:
    app: redis-commander
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081 # front-end: Note: A Service can map any incoming port to a targetPort. By default and for convenience, the targetPort is set to the same value as the port field

