version: '2'

services:

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    # add user id with `id -u` to grant grafana has privilage with specified folder
    user: "${UID}:${GID}"
    volumes:
     - "./grafanastroagedata:/var/lib/grafana"
    environment:
      GF_INSTALL_PLUGINS: percona-percona-app
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
