apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis
spec:
  type: NodePort # use NAT inside k8s
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379 # front-end: Note: A Service can map any incoming port to a targetPort. By default and for convenience, the targetPort is set to the same value as the port field

