apiVersion: v1
kind: Service
metadata:
  name: nsqd-service
  labels:
    app: nsqd
spec:
  clusterIP: None # 不使用NAT IP
  # type: LoadBalancer # use extenal IP
  # type: NodePort # use NAT inside k8s
  selector:
    app: nsqd
  ports:
    - name: http
      protocol: TCP
      port: 4151
      targetPort: 4151
    - name: tcp
      protocol: TCP
      port: 4150
      targetPort: 4150
