version: '2'

services:
  redis-commander:
    container_name: redis-commander
    networks:
      - proxy-network
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=redis:redis:6379:0:yourpassword
    ports:
      - "8081:8081"

  redis:
    container_name: redis
    command: redis-server --requirepass yourpassword
    image: redis
    restart: always
    # command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge