version: "3"

networks:
  proxy-net:
    driver: bridge

services:
  authserver:
    networks:
      - proxy-net
    image:  nginx:1.13.7
    expose:
      - 80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      
  proxy:
    networks:
      - proxy-net
    image:  nginx:1.13.7
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf