- name: Create instance(s)
  hosts: localhost

  vars:
    service_account_email: 704960288977-compute@developer.gserviceaccount.com
    credentials_file: ../../gcptestansible.json
    project_id: crack-will-209815
    machine_type: n1-standard-1
    image: debian-7
    gcp_instance_name: dev1,dev2,dev3

  tasks:
   - 
     name: Launch instances
     gce:
         instance_names: "{{ gcp_instance_name }}"
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
         metadata : '{ "startup-script" : "ping -c 3 127.0.0.1" }'